### ISSUE TITLE
Lazy load Routes for load optimization

### ISSUE THREAD

**Issue by obr42** [beer-garden/react-ui#113]
Do we want to implement [route-based code splitting](https://17.reactjs.org/docs/code-splitting.html#route-based-code-splitting)? Lazy loading can be applied to `Routes.tsx` to only load components for a page once the user actually attempts to access the page. It should help speed up initial rendering for the app by delaying rendering for components that aren't currently needed. I would recommend lazy loading all components that are assigned to a Route `element` except `RequireAuth` because that is used throughout the app. This may require some refactoring so that the components have a default export, as that is what is required by [react's lazy loading function](https://17.reactjs.org/docs/code-splitting.html#reactlazy).

It also might be good to add at least one top level [error landing page](https://17.reactjs.org/docs/error-boundaries.html) to attempt to handle errors loading the components - but unfortunately seems like it has to be a class component which is contradictory to us wanting to use function components, but it might be unavoidable if the error boundary is something we need for lazy loading to have a smooth user experience.

analyze bundle size: https://create-react-app.dev/docs/analyzing-the-bundle-size/

**Comment by jlrpnbbngtn** [comment]
After a brief discussion, it's agreed these are wise additions.
