### ISSUE TITLE
Table heading spacing

### ISSUE THREAD

**Issue by obr42** [beer-garden/react-ui#131]
After making the page headings consistent, pages with tables now have a large gap of blank space. This is because of where the filter and column select icons are. We should move them to be inline with any other buttons on the table and try to decrease the amount of white space. Should probably wait until #102 is done as that is doing table work that may be helpful

Currently:

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/107439850/190440211-05f00368-c8f6-488e-aedf-af0e13fb7740.png)

Desired:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/107439850/190440253-1b5563c6-c699-4393-8f32-122bf6ee4f8a.png)

**Comment by jlrpnbbngtn** [comment]
The other components (checkboxes, *refresh* button) in the images are passed in as children. Anything passed in as a child to the table goes there. This should just be a matter of rearranging where the children go, i.e. the children and filter/column button (when they're displayed) will go on the same "row".
