### ISSUE TITLE
Drink it again button

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/react-ui#16]
I think it would be pretty helpful to have a button similar to `Pour it Again` that would immediately re-execute the request.

The use-case I'm thinking is mostly for info-type requests. If I'm troubleshooting something where I'm modifying an external system (so the request parameters don't change) having to wait for the command page to re-render and then click `Make request` is just wasted time.

Admittedly, this could be dangerous for non-idempotent commands. So I'd be OK with only allow this for INFO commands.

**Comment by scott-taubman** [comment]
We could do this, but if we do the buttons need better labels.  "Drink it Again" and "Pour it Again" are not really distinguishable in terms of what they're going to do.
