### ISSUE TITLE
Provide 404-like for non-existent Job

### ISSUE THREAD

**Issue by jlrpnbbngtn** [beer-garden/react-ui#216]
If an individual job URL is mistyped or if it's been deleted and the page returned to, we see 3 spinners and a red snackbar.

Change that to 0 spinners (also don't show the *Trigger* and *Request Template* cards) and an informative alert instead of a snackbar.

This change will be visible *only* when fetching the Job fails on page load. Other error handling, for example if there's a problem when pushing the *Delete Job* button, remains the same.

**Comment by scott-taubman** [comment]
This appears to have been resolved with other error handling changes.  Closing as OBE.
