### ISSUE TITLE
Search bar tweaks

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/react-ui#23]
Couple improvements to the search bar:

- We need a hard limit on the number of rows the search bar dropdown can display. I feel like 15-20 would be a good starting point?
- If the search term results in an empty result set it displays a little tiny empty box. We should either display nothing or some message like "No results".
- This is a little weird, but I see a case where there's a weird gap in the commands. I'm seeing it with the "dynamic" plugin installed and searching for "as" - there's a gap right before "say_specific_dictionary_with_instance_name_key", and then that command is indented less than the others. Maybe because that command takes up the entire width of the dropdown? Let me know if you can't replicate and I'll try to get a screenshot.
- When the search bar gets the focus, any text that's already in there should be highlighted so new typing will start fresh. OR just clear the text when the user clicks on something in the dropdown.

**Comment by scott-taubman** [comment]
This all sounds specific to the search in the angular UI.  Closing.
