### ISSUE TITLE
Job update page loses data on refresh

### ISSUE THREAD

**Issue by west270** [beer-garden/react-ui#274]
The job update page loses the job data when the page is refreshed.

Possible solution would be to include the job id in the url, so the job can be retrieved from the backend. 
Another solution would be to change the route to be `api/#/jobs/update/6387acdf05e7bdd2ceced72c` use id to retrieve job then use the job to get command.

**Comment by jlrpnbbngtn** [comment]
This is no longer the case with an update to the job update code. It now correctly throws an error when the page is refreshed (i.e. the only supported way to get to a job update page is to use the "Job Update" button).
