### ISSUE TITLE
Update Systems Admin Page

### ISSUE THREAD

**Issue by TheBurchLog** [beer-garden/react-ui#30]
The System Admin Page needs to be redesigned. If you have a system that is deployed on multiple namespaces or has a ton of instances it gets uneven on the page. So we should find a way to clean this up and present it better to the Admins.

Edited to add info from beer-garden/beer-garden#778:
> The System Admin page is becoming very unbalanced when a plugin has multiple deployments across various namespaces and instances. We need to address a better way to visually display this data. 
>
>The big things to consider:
> * Grouping of like Systems either by Namespace or System Name
> * Functions that target the Namespace-System-Version and the Instance
> * How to give admins a quick view of everything online vs offline

**Comment by scott-taubman** [comment]
Blocked by #1
