### ISSUE TITLE
Create values for the dark theme that are more attractive.

### ISSUE THREAD

**Issue by jlrpnbbngtn** [beer-garden/react-ui#54]
The color scheme for the dark theme comes from the out-of-the-box values provided by MUI. This is essentially a solid black background, which is hard on the eyes. The contrast with, for example, buttons and tables is quite harsh.

The code in `src/components/UI/Theme/Theme.ts` is where the MUI theme is loaded and this is where customizations should likely happen.

- [ ] Investigate the available options from the MUI documentation ([this](https://mui.com/material-ui/customization/default-theme/) might be a good place to start).
- [ ] Find values that create a dark theme that is more in line with good design.
- [ ] (optional) Also find values to make the light theme be a little more inviting.
- [ ] (optional) Create one or two additional themes. This will involve updating the code in `src/components/UI/NavigationBar` to make the additions selectable by the user.

**Comment by catattack05** [comment]
It looks like we should be able to do most of the style changes from `src/components/UI/Theme/Theme.ts`. Besides the existing palette sections that will change the colors on a large scale, we can add a section that looks like this for each component that will override the palette and let us tweak things so they work better with each other. 

`components: { 
    ComponentName: {
        styleOverrides: { *some stuff here* }
     } 
}`

**Comment by catattack05** [comment]
We want to make sure the link colors in the dark theme are not the current ugly blue

**Comment by scott-taubman** [comment]
Totally naive question here, but is there not a repository of themes or color palettes out there that we could just use?  Material UI seems sufficiently big that I would think some community around such things would exist.

**Comment by catattack05** [comment]
There are definitely a lot of different color palettes out there, and I'm mostly using ones other people have come up with right now. I haven't run across anyone who put them all in code beyond basic examples, and I added more code besides the basics since just defining a primary and secondary color made things looks a little strange
