### ISSUE TITLE
Add timezone options to date pickers (used, for example, in table filters)

### ISSUE THREAD

**Issue by jlrpnbbngtn** [beer-garden/react-ui#66]
At this time, this affects the date pickers shown in the filter popout on the Requests page, but a solution should be general enough to be adopted elsewhere without major headaches.

The logic that the date pickers (on that page) call assumes UTC for entered dates, which is not the correct way to go. As it turns out, the picker components themselves are agnostic as to timezone. That is controlled by the *Localization.Provider*, currently provided in `App.tsx`.

Consequently, the approach that may make the most sense is for there to be a globally defined timezone for the app. This could potentially be something accessible via the option menu.

A fix would need to address several issues:

1. If there *isn't* a globally defined timezone, we must provide a way (in the popout on that page) to specify the timezone. It is probably out of scope to look into overriding/extending the MUI component, so this should probably be an additional component added to the popout.
2. Have dates then provided by the `DesktopDateTimePicker`s reflect that timezone, regarless of whether the global timezone is defined or not.
3. Have components that work with the dates (e.g. the MUI `Chip`s displayed by the `FilterChipBar` component) reflect that timezone.
4. Have logic that uses dates created by these components correctly convert them to a format usable by the backend, which in the case of filters expects the number of milliseconds since the epoch.
5. There will be other places where a datetime picker will be used. For example, on the scheduling page (a WIP), dates and times are important. If a timezone is defined globally, a design decision will have to be made as to whether scheduling can override that timezone. In other words, a user could set a global timezone of UTC but then schedule a job using local time.

**Comment by scott-taubman** [comment]
Let's just assume a global timezone of UTC on both the backend and frontend.  We'll want any date pickers to at least make it clear that UTC is the timezone we're operating in.
