### ISSUE TITLE
System Management Admin - Responsive Alerts

### ISSUE THREAD

**Issue by obr42** [beer-garden/react-ui#88]
The alert colors/icons render perfectly when the page is loaded. However, if user changes status of any of the instances via the buttons on the UI, the status is not ever updated. There is currently an implementation in the instance pop-up menu "start/stop instance" that gets the updated instance status and returns it to the menu item. However, the information does not filter up to the other Alerts, and it seems to not trigger React to update the view in a timely fashion. Figure out a way to make this feature work better and not just on page load/refresh. And don't forget it should work for if the system > start/stop all buttons are pressed as well

**Comment by knolnsokn** [comment]
Going to do the following

- [ ] Fix the bug in #182 so that the Stop Instance dropdown button on the System Admin Card works
- [ ] Update the useSystems hook to refetch when there is an INSTANCE_UPDATED event occurs
