### ISSUE TITLE
Refactor out CacheService

### ISSUE THREAD

**Issue by obr42** [beer-garden/react-ui#96]
We want hooks over services. The useLoclStorage hook already exists - we just need to convert all remaining references to CacheService. At least used in pages/SystemAdmin/SystemAdmin/tsx

FYI [this](https://github.com/beer-garden/react-ui/blob/42ef7ecd6c3712286b8f84554c1548678dd250bd/src/components/UI/NavigationBar/NavigationBar.tsx#L19) is an example of useLocalStorage being used in recent work.

Service file should be deleted once no longer used.

**Comment by west270** [comment]
`CacheService` has been removed from `pages/SystemAdmin/SystemAdmin/tsx`.
The remaining files with references that need refactored or removed are:
- [ ] `components/command_view_form.tsx`
- [ ] `components/table.tsx`
- [ ] `pages/RequestView/RequestView.tsx`
