### ISSUE TITLE
Don't run tests on git push

### ISSUE THREAD

**Issue by jessica-obrien** [beer-garden/react-ui#97]
There is a github hook that runs all tests on each push, but it probably shouldn't. Once we have more of the codebase tested that could tie up the terminal for some minutes. There is also a concern that tests might not always be in a passing state on purpose - don't want that to block ability to push code. Triple check tests run in PR pipeline before accepting merge to not run in terminal.

**Comment by jlrpnbbngtn** [comment]
Combining with #98 because it's easiest to fix both at the same time.
